<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN15I51216GR512" failures="1" tests="8" name="Surefire test" time="111.371" errors="0" timestamp="2025-02-18T00:45:30 IST">
  <testcase classname="nnd.TestCases.DB_LoginTest" name="inValidUserLogin" time="8.557"/>
  <testcase classname="nnd.TestCases.DB_LoginTest" name="inValidUserLogin" time="8.472"/>
  <testcase classname="nnd.TestCases.DB_LoginTest" name="validUserLogin" time="5.52"/>
  <testcase classname="nnd.TestCases.DB_LoginTest" name="validUserLogin" time="5.469"/>
  <testcase classname="nnd.TestCases.DB_HomeTest" name="verifyPurchaseItem" time="7.843"/>
  <testcase classname="nnd.TestCases.DB_RegisterTest" name="invalidUserSignUp" time="10.556"/>
  <testcase classname="nnd.TestCases.DB_RegisterTest" name="invalidUserSignUp" time="10.462"/>
  <testcase classname="nnd.TestCases.DB_RegisterTest" name="validUserSignUp" time="10.413">
    <failure type="java.lang.AssertionError" message="Signup failed expected [Sign up successful.] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: Signup failed expected [Sign up successful.] but found [This user already exist.]
at nnd.Pages.DB_RegisterPage.clickSignUp(DB_RegisterPage.java:67)
at nnd.TestCases.DB_RegisterTest.validUserSignUp(DB_RegisterTest.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- validUserSignUp -->
</testsuite> <!-- Surefire test -->
