<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN15I51216GR512" failures="1" tests="8" name="Demo Blaze Functional Tests" time="101.49" errors="0" timestamp="2025-02-18T01:40:17 IST">
  <testcase classname="nnd.TestCases.DB_RegisterTest" name="invalidUserSignUp" time="10.368"/>
  <testcase classname="nnd.TestCases.DB_RegisterTest" name="invalidUserSignUp" time="10.919"/>
  <testcase classname="nnd.TestCases.DB_RegisterTest" name="validUserSignUp" time="10.787">
    <failure type="java.lang.AssertionError" message="Signup failed expected [Sign up successful.] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: Signup failed expected [Sign up successful.] but found [This user already exist.]
at nnd.Pages.DB_RegisterPage.clickSignUp(DB_RegisterPage.java:67)
at nnd.TestCases.DB_RegisterTest.validUserSignUp(DB_RegisterTest.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validUserSignUp -->
  <testcase classname="nnd.TestCases.DB_LoginTest" name="validUserLogin" time="5.367"/>
  <testcase classname="nnd.TestCases.DB_LoginTest" name="validUserLogin" time="5.351"/>
  <testcase classname="nnd.TestCases.DB_LoginTest" name="inValidUserLogin" time="8.38"/>
  <testcase classname="nnd.TestCases.DB_LoginTest" name="inValidUserLogin" time="8.343"/>
  <testcase classname="nnd.TestCases.DB_HomeTest" name="verifyPurchaseItem" time="8.002"/>
</testsuite> <!-- Demo Blaze Functional Tests -->
